# SPDX-License-Identifier: AGPL-3.0-or-later
# Boomerang-Injection via mod_substitute

Alias /rum/ /opt/rum/

<Directory /opt/rum>
    Require all granted
    Options -Indexes
</Directory>

PassEnv OTEL_SDK_DISABLED
<If "reqenv('OTEL_SDK_DISABLED') != 'true'">
    AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE text/html
    Substitute "s|</head>|<script src=\"/rum/boomerang.js\"></script><script src=\"/rum/plugins/rt.js\"></script><script src=\"/rum/plugins/navtiming.js\"></script><script src=\"/rum/plugins/restiming.js\"></script><script src=\"/rum/plugins/painttiming.js\"></script><script src=\"/rum/plugins/eventtiming.js\"></script><script src=\"/rum/boomerang-opentelemetry.js\"></script><script src=\"/rum/boomerang-init.js\"></script></head>|i"
</If>
