# SPDX-License-Identifier: AGPL-3.0-or-later

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:8080"
            - "http://webtrees:80"
          allowed_headers:
            - "*"
          max_age: 7200

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  file:
    path: /artifacts/traces.json
    append: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, file]
