# SPDX-License-Identifier: AGPL-3.0-or-later

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  file:
    path: /artifacts/traces.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, file]
